server:
  port: 80
  tomcat:
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
spring:
  datasource:
    url: jdbc:mysql://192.168.48.129:3306/secondkill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: littleBoy1502@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.48.129
    port: 6379


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

rocketmq:
  name-server: 192.168.48.129:9876
  producer:
    transaction:
      topic: transaction-my-topic
    enable: true
    topic: test-topic
    group: my-group